### ISSUE TITLE
Issue with Sass version – Unicode values converted to glyphs

### ISSUE THREAD

**Issue by vanokhin** [ForkAwesome/Fork-Awesome#139]
## Description

I’m trying to compile the `SASS` version. I use the default sass command line compiler installed via npm.

```bash
npm i -g sass

sass --version
>> 1.15.2 compiled with dart2js 2.1.0

which sass
>> /usr/local/bin/sass

sass fork-awesome/scss/fork-awesome.scss fork-awesome.css
```

The resulting CSS file looks ok, but there is an issue – content values are replaced with the actual Unicode glyphs:

![screenshot](https://user-images.githubusercontent.com/1898673/49928130-88687580-fed0-11e8-838b-9b763f1c939e.png)

```css
/* fork-awesome.css */

.fa-glass:before {
  content: "";
}

.fa-music:before {
  content: "";
}
```

I know this issue is related to the SASS compiler itself and not to the ForkAwesome (which is Awesome, btw). But why not to prevent such behavior?

## Possible solution

We can remove backslash from sass variables and add it later when defining CSS classes using the following approach:

```scss
// Addition to the _mixins.scss file

@function backslash-it($value) {
  @return #{'"\\' + $value + '"'};
}
```

```scss
// _icons.scss:665

.#{$fa-css-prefix}-500px:before { content: backslash-it($fa-var-500px); }
```

And how variables may look then:

```scss
// _variables.scss:14

$fa-var-500px: "f26e";
$fa-var-activitypub: "f2f2";
```

## Additional comments

I’d be happy to make a pull request if you’re ready to review and accept it.
