### ISSUE TITLE
Proposal: use $fa-css-prefix in animation names or create a separate variable

### ISSUE THREAD

**Issue by vanokhin** [ForkAwesome/Fork-Awesome#140]
## Description

As the title says, maybe it would be better to use unique animation names to avoid possible conflicts with other builds.

### SASS version

This is how the `_animated.scss` file may look like:

```scss
// Spinning Icons
// --------------------------

.#{$fa-css-prefix}-spin {
  -webkit-animation: #{$fa-css-prefix}-spin 2s infinite linear;
          animation: #{$fa-css-prefix}-spin 2s infinite linear;
}

.#{$fa-css-prefix}-pulse {
  -webkit-animation: #{$fa-css-prefix}-spin 1s infinite steps(8);
          animation: #{$fa-css-prefix}-spin 1s infinite steps(8);
}

@-webkit-keyframes #{$fa-css-prefix}-spin {
  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(359deg);
            transform: rotate(359deg);
  }
}

@keyframes #{$fa-css-prefix}-spin {
  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(359deg);
            transform: rotate(359deg);
  }
}
```

### LESS version

And this is the `animated.less` version:

```less
// Animated Icons
// --------------------------

.@{fa-css-prefix}-spin {
  -webkit-animation: ~'@{fa-css-prefix}-spin' 2s infinite linear;
          animation: ~'@{fa-css-prefix}-spin' 2s infinite linear;
}

.@{fa-css-prefix}-pulse {
  -webkit-animation: ~'@{fa-css-prefix}-spin' 1s infinite steps(8);
          animation: ~'@{fa-css-prefix}-spin' 1s infinite steps(8);
}

@-webkit-keyframes ~'@{fa-css-prefix}-spin' {
  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(359deg);
            transform: rotate(359deg);
  }
}

@keyframes ~'@{fa-css-prefix}-spin' {
  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(359deg);
            transform: rotate(359deg);
  }
}
```

## PR?

I’d be happy to make a pull request. Just ask me.
